FCards/Cards/urls.py
from django.urls import path
from . import views, learn

urlpatterns = [
    path('add_set/', views.add_folder, name='add_folder'),
    path('home/', views.home, name='home'),
    path('delete_set/<int:set_id>/', views.delete_folder, name='delete_folder'),
    path('edit_set/<int:set_id>/', views.edit_folder, name='edit_folder'),
    path('copy_set/<int:set_id>/', views.copy_folder, name='copy_folder'),
    path('view_set/<int:set_id>/', views.view_folder, name='view_folder'),
    path('view_set_public/<int:set_id>/', views.view_folder_public, name='view_folder_public'),
    path('add_multicard/<int:set_id>/', views.add_multicard, name='add_multicard'),
    path('add_many/<int:set_id>/', views.add_many, name='add_many'),
    path('edit_multicards/<int:set_id>/', views.edit_multicards, name='edit_multicards'),
    path('delete_multicards/<int:set_id>/<int:m_card_id>/', views.delete_multicards, name='delete_multicards'),
    path('edit_multicards_save/<int:set_id>/<int:m_card_id>/', views.edit_multicards_save, name='edit_multicards_save'),
    path('edit_all_multicards/<int:set_id>/', views.edit_all_multicards, name='edit_all_multicards'),
    path('learn/learn/<int:set_id>/', learn.learn, name='learn'),
    path('learn/write/<int:set_id>/', learn.write, name='write'),
    path('learn/flashcards/<int:set_id>/', learn.flashcards, name='flashcards'),
    path('reset_progress/<int:set_id>/', views.reset_progress, name='reset_progress'),
    path('make_public/<int:set_id>/', views.make_public, name='make_public'),
    path('refresh_update/<int:set_id>/', views.refresh_update, name='refresh_update'),
    path('repair_translations/<int:set_id>/', views.repair_translations, name='repair_translations'),
    path('public_sets/', views.public_sets, name='public_sets'),
    path('demo/', views.demo_welcome, name='demo'),
]

FCards/Cards/models.py
from django.db import models
from . import langcodes
from django.contrib.auth.models import User
from datetime import datetime
# from googletrans import Translator
# from django.db.models import F


# Create your models here.

class CardFolder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    create_date = models.DateField(auto_now_add=True)
    edit_date = models.DateField(auto_now=True)
    lang1 = models.CharField(max_length=5, choices=langcodes.LangCodes0, default="en")
    lang2 = models.CharField(max_length=5, choices=langcodes.LangCodes0, default="pl")
    lang3 = models.CharField(max_length=5, choices=langcodes.LangCodes, default="ja", blank=True)
    lang4 = models.CharField(max_length=5, choices=langcodes.LangCodes, default="es", blank=True)
    lang5 = models.CharField(max_length=5, choices=langcodes.LangCodes, default="de", blank=True)
    score = models.SmallIntegerField(default=0)
    comment = models.CharField(max_length=400, blank=True)
    public = models.BooleanField(default=False)
    show_multicard_comment = models.BooleanField(default=True)
    being_edited = models.BooleanField(default=False)

    def get_langs(self, item=False):
        langs = (self.lang1, self.lang2, self.lang3, self.lang4, self.lang5)
        lang_choices = []
        lang_values = []
        lang_keys = []
        for i in langs:
            if i != "":
                value = langcodes.LangCodesDict[i].capitalize()
                lang_choices.append((i, value))
                lang_values.append(value)
                lang_keys.append(i)
        if item == 'value':
            return lang_values
        if item == 'key':
            return lang_keys
        else:
            return lang_choices

    def langs_keys(self):
        langs = [self.lang1, self.lang2, self.lang3, self.lang4, self.lang5]
        true_langs = []
        for i in langs:
            if i != "":
                true_langs.append(i)
        return true_langs

    def langs_no(self):
        return len(self.get_langs())

    langs_no.short_description = "No of languages"

    def __str__(self):
        return self.name


class MultiCard(models.Model):
    cards_folder = models.ForeignKey(CardFolder, on_delete=models.CASCADE)
    score = models.SmallIntegerField(default=0)
    comment = models.CharField(max_length=400, blank=True)
    definition = models.CharField(max_length=400, blank=True)
    rates = models.SmallIntegerField(default=0)
    rating = models.SmallIntegerField(default=0)
    mastered = models.BooleanField(default=False)
    priority = models.SmallIntegerField(default=10)
    being_edited = models.BooleanField(default=False)
    last_studied = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)

    def max_languages(self):
        return self.cards_folder.langs_no()

    def all_translations(self):
        mains = []
        cards = self.card_set.all()
        for card in cards:
            mains.append(card.language + ": " + card.main)
        return mains

    def check_if_mastered(self):
        langs = self.cards_folder.get_langs(item='key')
        mastered = True
        for lang in langs:
            if not Card.objects.get(multi_card=self, language=lang).mastered:
                mastered = False
        self.mastered = mastered
        self.save()

    # image = models.ImageField(upload_to='uploads/')
    # choice_text = models.CharField(max_length=200)
    # votes = models.IntegerField(default=0)


class Card(models.Model):
    multi_card = models.ForeignKey(MultiCard, on_delete=models.CASCADE)
    cards_folder = models.ForeignKey(CardFolder, on_delete=models.CASCADE)
    language = models.CharField(max_length=5, choices=langcodes.LangCodes, default="en")
    main = models.CharField(max_length=50)
    automated = models.BooleanField(default=False)
    score = models.SmallIntegerField(default=0)
    pronunciation = models.CharField(max_length=200, blank=True, null=True)
    synonyms = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=400, blank=True)
    rating = models.SmallIntegerField(default=0)
    mastered = models.BooleanField(default=False)
    priority = models.SmallIntegerField(default=0)
    show_answer = models.BooleanField(default=True)

    def check_show(self):
        # If card has been showed only for the game or if it is it's first appearance it will by un-showed.
        # If card is mastered, nothing changes.
        if not self.mastered:
            if self.score < 10:
                self.score = 10
            self.show_answer = False
            self.save()

    def check_answer(self, word_to_check):
        word_to_check = word_to_check.capitalize()
        # If answer is correct
        if word_to_check and (self.main in word_to_check or (self.synonyms and self.synonyms in word_to_check)):
            points = 20
            self.score += 20
            self.multi_card.score += 20
            self.multi_card.priority += 1
            self.priority += 1
        # If answer is incorrect
        else:
            points = -15
            self.score -= 15

        self.update_numbers()

        return points

    def update_numbers(self):
        if self.score > 100:
            self.score = 100
            self.mastered = True
            self.show_answer = True
            self.multi_card.check_if_mastered()
        elif self.score < 85:
            self.mastered = False
            if self.score < 10:
                self.show_answer = True
                if self.score < 0:
                    self.score = 0
        if self.priority < 2:
            self.priority = 2
        # MultiCard.objects.filter(cards_folder=self.cards_folder).update(priority=F('priority') - 1)
        if self.multi_card.priority < 2:
            self.multi_card.priority = 2
        self.multi_card.last_studied = datetime.now()
        self.multi_card.save()
        self.save()

    def add_score_flashcards(self, score_priority):
        self.score += score_priority[0]
        self.multi_card.score += score_priority[0]
        self.multi_card.priority = score_priority[1]
        self.priority = score_priority[1]

        self.update_numbers()

    def __str__(self):
        return self.main

FCards/Cards/forms.py
from django.forms import ModelForm
from .models import CardFolder
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class FolderForm(ModelForm):
    class Meta:
        model = CardFolder
        fields = ['name', 'lang1', 'lang2', 'lang3', 'lang4', 'lang5', 'comment']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Name for the set')}),
            'lang1': forms.Select(attrs={'class': 'form-control'}),
            'lang2': forms.Select(attrs={'class': 'form-control'}),
            'lang3': forms.Select(attrs={'class': 'form-control'}),
            'lang4': forms.Select(attrs={'class': 'form-control'}),
            'lang5': forms.Select(attrs={'class': 'form-control'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        }
        labels = {
            'name': _('Set name'),
            'lang1': _('1st language'),
            'lang2': _('2nd language'),
            'lang3': _('3rd language'),
            'lang4': _('4th language'),
            'lang5': _('5th language'),
            'comment': _('Your comment'),
        }

    def clean(self):
        cleaned_data = super().clean()
        lang1 = cleaned_data.get("lang1")
        lang2 = cleaned_data.get("lang2")
        lang3 = cleaned_data.get("lang3")
        lang4 = cleaned_data.get("lang4")
        lang5 = cleaned_data.get("lang5")

        langs = []
        for lang in (lang1, lang2, lang3, lang4, lang5):
            if lang:
                langs.append(lang)

        def check_if_duplicates(listOfElems):
            ''' Check if given list contains any duplicates '''
            if len(listOfElems) == len(set(listOfElems)):
                return False
            else:
                return True

        result = check_if_duplicates(langs)
        if result:
            raise ValidationError(_("Every language must be different."))


class CardsForm(forms.Form):
    # MultiCard
    # multi_comment = forms.CharField(max_length=400, required=False, widget=forms.TextInput(attrs={'class': 'form'
    #                                                                                                        '-control'}))
    # multi_definition = forms.CharField(max_length=400, required=False, widget=forms.TextInput(attrs={'class': 'form'
    #                                                                                                           '-control'}))

    # Card
    language = forms.CharField(max_length=5)
    main = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    automated = forms.BooleanField(initial=False)
    pronunciation = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={'class': 'form'
                                                                                                           '-control'}))
    synonyms = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    comment = forms.CharField(max_length=400, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))

    # class Meta:
    #     widgets = {
    #         'automated': forms.HiddenInput(),
    #         'language': forms.HiddenInput(),
    #         'main': forms.CharField(attrs={'class': 'form-control'}),
    #         'pronunciation': forms.CharField(attrs={'class': 'form-control'}),
    #         'synonyms': forms.CharField(attrs={'class': 'form-control'}),
    #         'comment': forms.CharField(attrs={'class': 'form-control'}),}

    # def __init__(self, *args, **kwargs):
    #     super(RawCardForm, self).__init__(*args, **kwargs)
    #     self.fields['language'] = forms.ChoiceField(
    #         choices=get_my_choices() )

FCards/Cards/templates/Cards/edit_all_multicards.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans 'Edit MultiCards' %}
{% endblock %}

{% block styles %}
<style>
.hiddenRow {
    padding: 0 !important;
}
</style>
<script>
$('.collapse').on('show.bs.collapse', function () {
    $('.collapse.in').collapse('hide');
});
</script>

{% load get_obj %}

{% endblock %}

{% block nav_buttons %}
<a class="btn btn-outline-info" href="{% url 'view_folder' set_id=folder.id %}">{% trans 'View' %}</a>
<a class="btn btn-outline-light" href="{% url 'learn' set_id=folder.id %}">{% trans 'Learn' %}</a>
<a class="btn btn-outline-warning" href="{% url 'edit_folder' set_id=folder.id %}">{% trans 'Edit Set' %}</a>
<button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#staticBackdrop">{% trans 'Add MultiCard' %}</button>
<button type="submit" form="form" class="btn btn-outline-success">{% trans 'Save changes' %}</button>
{% endblock nav_buttons %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="text-dark">
        <h1 class="display-5">{% blocktrans with name=folder.name %}Here are your MultiCards in {{name}}.{% endblocktrans %}</h1>
        <p class="lead">{{ folder.comment }}</p>
        <p>{% trans 'Use CTRL+F to quickly find your cards.' %}</p>
        <a class="btn btn-outline-dark" href="{% url 'edit_multicards' set_id=folder.id %}">{% trans 'You can change the view back to single edit here.' %}</a>
    </div>
  </div>
</div>

<form method="POST" id="form" action=".">{% csrf_token %}
<div class="table-responsive">
 <table class="table table-sm table-light">
    <thead class="thead-dark">
        <th style="width: 1%"><h5><b>
            #
        </b></h5></th>
          {% for k, v in folder.get_langs %}
          <th class="text-center" style="min-width:140">
              <h5><b>
                  {{ v|upper }}
              </b></h5>
          </th>
          {% endfor %}
    </thead>
     {% for multicard in folder.multicard_set.all %}
        <tr>
            <td style="width:1%">
                <b><br/>{{ forloop.counter }}.</b>
            </td>
            {% for lang in folder.langs_keys %}
                {% get_card lang multicard as card %}
                    <td style="width: {{width}}%">
                        <div class="text-center"><b><br/>{{ card.main }}</b></div>
                    </td>
            {% endfor %}
        </tr>
        <tr class="table-active table-borderless">
            <td style="width:1%">

                <span class="form-control-plaintext text-center font-weight-bold pt-0"><a data-toggle="tooltip" title="Word">W</a></span>
                <span class="form-control-plaintext text-center font-weight-bold pt-3"><a data-toggle="tooltip" title="Pronunciation">P</a></span>
                <span class="form-control-plaintext text-center font-weight-bold pt-3"><a data-toggle="tooltip" title="Synonym">S</a></span>
                <span class="form-control-plaintext text-center font-weight-bold pt-3"><a data-toggle="tooltip" title="Comment">C</a></span>
            </td>
            {% for k, v in langs %}
             {% get_card k multicard as card %}
              <td>
                  <p>
                    <input type="text" name="main{{k}}{{multicard.id}}" class="form-control form-control-sm" maxlength="50" required value="{{card.main}}">
                  </p>
                  <p>
                    <input type="text" name="pronunciation{{k}}{{multicard.id}}" class="form-control form-control-sm" maxlength="50" value="{{card.pronunciation}}">
                  </p>
                  <p>
                    <input type="text" name="synonyms{{k}}{{multicard.id}}" class="form-control form-control-sm" maxlength="50" value="{{card.synonyms}}">
                  </p>
                  <p>
                    <input type="text" name="comment{{k}}{{multicard.id}}" class="form-control form-control-sm" maxlength="50" value="{{card.comment}}">
                  </p>
              </td>
            {% endfor %}
        </tr>
        <tr>
          <td colspan="{{length|add:'1'}}">
            <div class="row" style="width:99%">
              <div class="col-auto">
                <input type="checkbox" class="btn btn-outline-danger" value=1 name="delete{{multicard.id}}" id="d{{multicard.id}}">
                  <label style="color:#d51e25" for="d{{multicard.id}}"><b>Delete</b></label>
                </div>
                  <div class="col-sm">
                    <p class="font-weight-bold"><span class="form-control-plaintext">Comment</span>
                    <input type="text" name="comment{{multicard.id}}" class="form-control" maxlength="400" placeholder="{% trans 'Comment for this MultiCard' %}" value="{{multicard.comment}}">
                  </p>
                  </div>
                  <div class="col-sm">
                    <p class="font-weight-bold"><span class="form-control-plaintext">Definition</span>
                      <input type="text" name="definition{{multicard.id}}" class="form-control" maxlength="400" placeholder="{% trans 'Definition for this MultiCard' %}" value="{{multicard.definition}}">
                  </p>
                  </div>

              </div>
          </td>
        </tr>
     <tr style="background-color:#292b2c">
        <td colspan="{{length|add:'1'}}"><br/></td>
     </tr>
        {% endfor %}
 </table>
 <button class="btn btn-success btn-block"><b>Save changes</b></button>
</div>
</form>

{% include 'Cards/add_mcards_modal.html' %}
{% endblock %}

FCards/Cards/templates/Cards/folder_being_updated.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans 'No access' %}
{% endblock title %}

{% block styles %}

{% endblock styles %}

{% block body %}

  <div class="container">
  <div class="container text-center">
      <br/>
      <br/>
      <br/>
    <h3>{% trans 'This Set is currently being updated.' %}</h3>
<h5>{% trans 'Please wait for all automatic translations to finish before changing this Set.' %}</h5>
    <br/>
              <a class="btn btn-block btn-outline-light" href="{% url 'refresh_update' set_id=folder.id %}">{% trans 'Refresh' %}</a>
      <br/>
      <br/>
  </div>
  </div>


{% endblock body %}

FCards/Cards/templates/Cards/index.html
{% extends "base.html" %}

{% block title %}
{% load i18n %}
{% blocktrans  %} Welcome {{ user }} {% endblocktrans %}
{% endblock %}

{% block styles %}
<style>
.hiddenRow {
    padding: 0 !important;
}
</style>
<script>
$('.collapse').on('show.bs.collapse', function () {
    $('.collapse.in').collapse('hide');
});
</script>
{% load get_obj %}

{% endblock %}

{% block nav_buttons %}
<a href="{% url 'account_overview' %}"><button type="button" class="btn btn-outline-warning">{% trans "Account" %}</button></a>
<a href="{% url 'public_sets' %}"><button type="button" class="btn btn-outline-primary">{% trans "Public sets" %}</button></a>
<a href="{% url 'add_folder' %}"><button type="button" class="btn btn-outline-secondary">{% trans "New set" %}</button></a>
{% endblock nav_buttons %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="text-dark">
      {% if user.cardfolder_set.all %}
        <h1>{% blocktrans with user=user %}Here are your sets to study, {{ user }}. {% endblocktrans %}</h1>
        <p class="lead">{% trans "Click on the set name to view its details." %}</p>
      {% else %}
        <h1>{% trans "Here will appear your CardSets, " %}{{ user }}.</h1>
        <p class="lead">
          <a href="{% url 'add_folder' %}"><button type="button" class="btn btn-outline-secondary my-1">{% trans "Create a new set" %}</button></a>
          <a href="{% url 'public_sets' %}"><button type="button" class="btn btn-outline-primary">{% trans "or copy from public ones." %}</button></a>
        </p>
      {% endif %}
    </div>
  </div>
</div>

  {% for folder in user.cardfolder_set.all %}
  <div>
    <table class="table table-hover table-dark table-borderless" style="border-collapse:collapse; margin-bottom: 0px">
      <thead>
        <tr data-toggle="collapse" data-target="#b{{folder.id}}" class="clickable collapse-row collapsed">
          <th colspan="{{folder.langs_no|add:'0'}}">
            <div class="row">
              <div class="col-4">
                <h3>
                 {{ folder.name }}
                </h3>
              </div>
              <div class="col-md-8">
                <div id="b{{folder.id}}" class="collapse">
                  <div class="text-right">
                    <a class="btn btn-sm btn-outline-light mb-1" href="{% url 'learn' set_id=folder.id %}">{% trans "Learn" %}</a>
                    <a class="btn btn-sm btn-outline-info mb-1" href="{% url 'view_folder' set_id=folder.id %}">{% trans "View" %}</a>
                    <a class="btn btn-sm btn-outline-success mb-1" href="{% url 'add_multicard' set_id=folder.id %}">{% trans "Add MultiCard" %}</a>
                    <a class="btn btn-sm btn-outline-primary mb-1" href="{% url 'edit_multicards' set_id=folder.id %}">{% trans "Edit MultiCards" %}</a>
                    <a class="btn btn-sm btn-outline-warning mb-1" href="{% url 'edit_folder' set_id=folder.id %}">{% trans "Edit Set" %}</a>
                    <a class="btn btn-sm btn-outline-secondary mb-1" href="{% url 'copy_folder' set_id=folder.id %}">{% trans "Copy" %}</a>
                    <button type="button" class="btn btn-sm btn-outline-danger mb-1" data-toggle="modal" data-target="#c{{folder.id}}">{% trans "Delete" %}</button>
                  </div>
                </div>
              </div>
            </div>
          </th>
        </tr>

        <tr>
          <th class="hiddenRow" colspan="{{folder.langs_no}}">
              <div id="b{{folder.id}}" class="collapse">
                <h6>{{ folder.comment }}</h6>
              </div>
            </th>
        </tr>
      </thead>
    </table>
  </div>
  <div class="table-responsive">
    <table class="table table-hover table-dark table-borderless" style="border-collapse:collapse;">
      <thead>
        <tr>
          {% for k, v in folder.get_langs %}
            <td class="hiddenRow" style="width: {{folder.get_langs|width}}%; min-width:140">
              <div id="b{{folder.id}}" class="collapse ml-2">
                <h5><b>{{ v|upper }}</b></h5>
              </div>
            </td>
          {% endfor %}
        </tr>
        </thead>
      {% if folder.multicard_set.all %}
        {% for multicard in folder.multicard_set.all %}
        <tr class="table-secondary text-dark">
          {% for lang in folder.langs_keys %}
          {% get_card lang multicard as card %}

            <td class="hiddenRow">
              <div id="b{{folder.id}}" class="collapse">
                {% if not card.main %}
                <a href="{% url 'repair_translations' set_id=folder.id %}" data-toggle="tooltip" title='{% trans "Page needs to be refreshed to see the changes. If new translations does not seem to appear, Click me." %}'>{% trans 'loading...' %}</a>
                {% elif card.main == 'Translation error' %}
                <a href="{% url 'repair_translations' set_id=folder.id %}" data-toggle="tooltip" title="{% trans 'Looks like a translation error have occurred. Click me to repeat translation process.' %}">{% trans 'Translation error' %}</a>
                {% else %}
                  <b>{{ card.main }}</b>
                {% endif %}
              </div>
            </td>
          {% endfor %}
          <td style="width:0.5%; white-space: nowrap;" class="hiddenRow">
            <div id="xb{{folder.id}}" class="collapse">
              .
            </div>
          </td>
        </tr>
        {% endfor %}
      {% else %}
        <tr class="table-secondary text-dark">
        <td colspan="{{folder.langs_no}}" class="hiddenRow">
          <div id="b{{folder.id}}" class="collapse">
            <b> {% trans "There are no cards in this set." %}</b>
          </div>
        </td>
          <td style="width:0.5%; white-space: nowrap;" class="hiddenRow">
            <div id="xb{{folder.id}}" class="collapse">
              .
            </div>
          </td>
        </tr>
      {% endif %}
    </table>
  </div>
  <hr/>

<div class="text-dark">
  <div class="modal fade" id="c{{folder.id}}" tabindex="-1" role="dialog" aria-labelledby="c{{folder.id}}Label">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="c{{folder.id}}Label">{% trans "Delete" %} {{folder.name}}?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>{% trans "Are you sure you want to delete set " %}"{{folder.name}}"?</p>
          {% if folder.multicard_set.all %}
          <p>{% blocktrans with folder.multicard_set.all|length as length %}This set consists of {{length}} MultiCards.{% endblocktrans %}</p>
          {% endif %}
        </div>
        <div class="modal-footer">
          <form method="POST" action="{% url 'delete_folder' set_id=folder.id %}">{% csrf_token %}
            <input type="submit" class="btn btn-danger" value="{% trans 'Yes, delete it.' %}"/>
          </form>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Abort" %}</button>
        </div>
      </div>
    </div>
  </div>
</div>
  {% endfor %}

{% endblock %}

{% block bodyend %}
{% endblock %}

FCards/Cards/templates/Cards/view_set_public.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{{folder.name}}
{% endblock %}

{% block styles %}
<style>
.hiddenRow {
    padding: 0 !important;
}
</style>
<script>
$('.collapse').on('show.bs.collapse', function () {
    $('.collapse.in').collapse('hide');
});
</script>

{% load get_obj %}

{% endblock %}

{% block nav_buttons %}
<a class="btn btn-outline-secondary" href="{% url 'copy_folder' set_id=folder.id %}">{% trans 'Copy Set' %}</a>
<a href="{% url 'public_sets' %}"><button type="button" class="btn btn-outline-primary">{% trans 'Public sets' %}</button></a>
{% endblock nav_buttons %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <div class="text-dark">
    <h1 class="display-4">{{ folder.name }}</h1>
    <p class="lead">{{ folder.comment }}</p>
    </div>
  </div>
</div>
  <div class="table-responsive">
    <table class="table table-hover table-dark" style="border-collapse:collapse;">
      <thead>
        <tr class="table-light text-dark">
          <td><h5><b>#</b></h5></td>
          {% for k, v in folder.get_langs %}
            <td style="width: {{folder.get_langs|width}}%; ; min-width:140">
                <h5><b>{{ v|upper }}</b></h5>
            </td>
          {% endfor %}
        </tr>
        </thead>
      {% if folder.multicard_set.all %}
        {% for multicard in folder.multicard_set.all %}
        <tr data-toggle="collapse" data-target="#a{{multicard.id}}" class="clickable collapse-row collapsed">
          <td><b>{{forloop.counter}}</b></td>
          {% for lang in folder.langs_keys %}
          {% get_card lang multicard as card %}

            <td>
                {% if not card.main %}
                <b>{% trans 'loading...' %}</b>
                {% else %}
                  <b>{{ card.main }}</b>
                {% endif %}
            </td>
          {% endfor %}
        </tr>
        <tr class="table-secondary">
        <td class="hiddenRow"></td>
          {% for lang in folder.langs_keys %}
          {% get_card lang multicard as card %}
          <td class="hiddenRow">
                <div id="a{{multicard.id}}" class="collapse">
                  <div class="text-dark">
                  {% if card.automated %}
                    <p>{% trans 'Auto-translated' %}</p>
                  {% endif %}
                  {% if card.pronunciation %}
                    <p>{% trans 'Pronunciation' %}: {{ card.pronunciation }}</p>
                  {% endif %}
                  {% if card.synonyms %}
                    <p>{% trans 'Synonym' %}: {{ card.synonyms }}</p>
                  {% endif %}
                  {% if card.definition %}
                    <p>{% trans 'Definition' %}: {{ card.definition }}</p>
                  {% endif %}
                  {% if card.comment %}
                    <p>{% trans 'Comment' %}: {{ card.comment }}</p>
                  {% endif %}
                </div>
              </div>
          </td>
          {% endfor %}

        </tr>
        {% endfor %}
      {% else %}
        <th colspan="{{folder.langs_no}}">
          {% trans 'There are no cards for this set.' %}
        </th>
      {% endif %}
    </table>
  </div>
  <hr/>

{% endblock %}